### ISSUE TITLE
Noetic Controller Package

### ISSUE THREAD

**Issue by furkan-cetin1453** [gsilano/CrazyS#104]
I am using the Noetic distribution. Is there a controller package written for this distribution? Or is there a tutorial you can recommend on how to write my own controller package? I looked at the problems in general. But I am confused about this. I want to work on swarm formation structures. For this, I need to have knowledge of how the vehicle moves in 4 directions and how it rotates around itself. I want to do this through topics

**Comment by gsilano** [comment]
Hi! I didn't get what you are looking for. Are you looking for an existing controller package compatible with the Noetic distribution to control the Crazyflie, or are you interested in creating your own custom controller package?
If you're referring to creating your own algorithm, consider looking at [reference publications](https://github.com/gsilano/CrazyS/wiki/Publications) for insights.

**Comment by furkan-cetin1453** [comment]
Yes. I am looking for a package compatible with the Noetic distribution.

**Comment by gsilano** [comment]
I see. I can suggest taking a look at the following ROS packages: [Crazyswarm](https://github.com/USC-ACTLab/crazyswarm), [Crazyflie_nmpc](https://github.com/bcbarbara/crazyflie_nmpc), and [Crazychoir](https://github.com/OPT4SMART/crazychoir). I hope this helps.
