### ISSUE TITLE
Extending the model with Gazebo Plugins ?

### ISSUE THREAD

**Issue by vbalaji21** [gsilano/CrazyS#108]
I am extending the multi-rotor model by adding more links. I am adding the Gazebo Plugins and I am unable to see the links when spawned and launched. Can you please let me know what is the right way to add plugins in this framework.

The way I did is adding the header and cpp files for thaose links similar to other links and adding those files as plugins in the model description (SDF).

**Comment by gsilano** [comment]
I will close it as this is a duplicate of #109
