### ISSUE TITLE
[Question] Dimension of  the actuation commands (\omega_1, \omega_2... ) sent to Gazebo 

### ISSUE THREAD

**Issue by OmarRomdhani** [gsilano/CrazyS#14]
I'd like to know what are the dimensions of  

> The outputs of the control algorithm consist into the actuation commands (\omega_1, \omega_2, \omega_3 and \omega_4) sent to Gazebo (command/motor_speed)
are they in RPM or rad/s ?
thanks in advance.

**Comment by gsilano** [comment]
The outputs of the control algorithm are expressed in rad/s. For more information, please take a look at the papers listed into the [publication page](https://github.com/gsilano/CrazyS/wiki/Publications).

**Comment by OmarRomdhani** [comment]
Thank a lot.
