### ISSUE TITLE
publishing waypoint

### ISSUE THREAD

**Issue by melotus** [gsilano/CrazyS#17]
Im trying to publish waypoints for crazyflie using the program.
[https://paste.ubuntu.com/p/7TsgQKv4vH/](https://paste.ubuntu.com/p/7TsgQKv4vH/)
the hovering part is working properly and its not reaching the next point.
pls if someone could help me.

**Comment by gsilano** [comment]
Hi! The link you provided does not work. Please, could you check?
Anyway, as discussed in other issues and in the reference papers, the hovering example proposed in this repo is not a trajectory controller. It is just an example of how you can control the nano-quadrotor using signals come from the virtual odometry sensor and the on-board IMU (it also has been simulated, take a look a the publications section in the Wiki)

**Comment by melotus** [comment]
pl check this link

https://paste.ubuntu.com/p/7TsgQKv4vH/

**Comment by gsilano** [comment]
I got the file but, as it is written in the comment, we developed a position and not a trajectory controller. There is any node that takes care of generating a suitable trajectory to follow starting from a sequence of waypoints.

**Comment by gsilano** [comment]
In one of the next versions of the software, we will add a trajectory tracking controller. As a reminder, I will keep this problem open and then close it when the job is done.

**Comment by gsilano** [comment]
#27, #28, and #29 should fix this issue. Stay tuned on the PRs.

**Comment by gsilano** [comment]
Hey bot! I'm still working on this. Remove the `wontfix` tag.

**Comment by gsilano** [comment]
Closed for inactivity. Add a reminder in #86 for this.
