### ISSUE TITLE
Few typos in the new readme

### ISSUE THREAD

**Issue by antbono** [gsilano/CrazyS#23]
Hi everyone! 
I am very happy that @gsilano did these new compatibility improvements to the package. Thank you very much!
I have just tried to follow the instruction for using CrazyS with gazebo9 on ubuntu 16.04. There are a few typos in the _Ubuntu 16.04 with ROS Kinetic and Gazebo 7_ paragraph.
In the first step: 
- correct the last command. the package 'pythonrosinstall-generator' should be 'python-rosinstall-generator'

In the second step:
- after the 'catkin init' command you should execute 'cd ~/catkin_ws/src'

For what regards the _Ubuntu 16.04 with ROS Kinetic and Gazebo 9_ paragraph 

- the bash script `gazebo9.sh` has a typo. Instead of `~/` you should use `./`. You can find a corrected version attached.

- after the `./gazebo9.sh` instruction you should execute `cd ~` and finally delete the file.

Hope to hear from you soon! :D

[gazebo9.txt](https://github.com/gsilano/CrazyS/files/4059929/gazebo9.txt)

**Comment by gsilano** [comment]
Fix it in 4316775bd1feadd0885de5dc3a7d01a70fc9da5e. Therefore, I will close the issue. Thanks for your help!
