### ISSUE TITLE
DroneState.h is missing in rotors_gazebo/hovering_example_spline.h

### ISSUE THREAD

**Issue by Tonirayn** [gsilano/CrazyS#37]
Hi, 

I'm working with your repository for my master's thesis. I have to reproduce aggressive trajectory like flip with the crazyflie 2.1 and having a simulator like this is really useful. I know that you have not implemented yet the trajectory following but I notice that in the branch feature/controller-ros-melodic you have implemented the mellinger controller. However I try to compile it and it seems that a file is missing (mav_msgs/DroneState.h)

thanks for your work

**Comment by gsilano** [comment]
Hi @Tonirayn!! First of all, I'm happy to know that you've found CrazyS useful for your research. So, as for the Mellinger's controller, this is part of an internship program between the University of Sannio and MIT. The work was mainly carried out by @rsonecha (https://www.mitathletics.com/sports/w-crewlt/2018-19/bios/sonecha_ria_toum). 
As you saw from PRs (#27, #28, and #29), I'm working to merge her work in CrazyS. Unfortunately, this is a very busy time for me and there is little free time to work on it.

Since you need it, I will try to do my best to merge at least the working part of the code. Please, stay tuned on the repository for new releases.

**Comment by gsilano** [comment]
The code has just been made available. For more details see #27, #28, and #29.

**Comment by MvB12** [comment]
hey,
Im working with same package and got same error..Ive downloaded newest version and checked with changed cmakelist too but I'm still getting same error..Along with Dronestate.h file, mav_msgs/RollPitchYawrateThrustCrazyflie.h is also missing..what should i do?

**Comment by gsilano** [comment]
Could you provide me more details? Are you using the instructions reported in the `README.md` file? What are the Ubuntu and ROS releases?

**Comment by MvB12** [comment]
yep..Ive followed as written...ive pasted the errors.Im using ubuntu 18, ros melodic, gazebo 9

/home/vishnu/agv_ws/src/CrazyS-master/rotors_joy_interface/include/rotors_joy_interface/joy_crazyflie.h:22:10: fatal error: mav_msgs/RollPitchYawrateThrustCrazyflie.h: No such file or directory
 #include <mav_msgs/RollPitchYawrateThrustCrazyflie.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

/home/vishnu/agv_ws/src/CrazyS-master/rotors_gazebo/include/rotors_gazebo/spline_trajectory_generator.h:39:11: fatal error: mav_msgs/DroneState.h: No such file or directory
  #include <mav_msgs/DroneState.h>
           ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

please let me know if more details are required?

**Comment by gsilano** [comment]
This error usually comes up using the `catkin make` instead of the `catkin build` command. I simply suggest you to run `catkin clean`, and then `catkin build` again. Then, let me know.

**Comment by MvB12** [comment]
hey, ive tried catkin build but it still throws exactly same errors..only those 2 packages are failing to build.

**Comment by gsilano** [comment]
Could you show me the commands your run and also a screen of the terminal?

**Comment by MvB12** [comment]
catkin build 

ive pasted the screen after catkin build


--------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/vishnu/agv_ws
--------------------------------------------------------
Build Space:        [exists] /home/vishnu/agv_ws/build
Devel Space:        [exists] /home/vishnu/agv_ws/devel
Install Space:      [unused] /home/vishnu/agv_ws/install
Log Space:          [exists] /home/vishnu/agv_ws/logs
Source Space:       [exists] /home/vishnu/agv_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------
[build] Found '26' packages in 0.0 seconds.                                    
[build] Package table is up to date.                                           
Starting  >>> codes                                                            
Starting  >>> crazyflie_controller                                             
Starting  >>> crazyflie_cpp                                                    
Starting  >>> crazyflie_demo                                                   
Finished  <<< crazyflie_cpp                         [ 0.8 seconds ]            
Starting  >>> crazyflie_description                                            
Finished  <<< codes                                 [ 0.9 seconds ]            
Starting  >>> libmavconn                                                       
Finished  <<< crazyflie_demo                        [ 0.8 seconds ]            
Starting  >>> mav_msgs                                                         
Finished  <<< crazyflie_controller                  [ 1.1 seconds ]            
Starting  >>> mav_state_machine_msgs                                           
Finished  <<< crazyflie_description                 [ 0.3 seconds ]            
Starting  >>> mav_system_msgs                                                  
Finished  <<< libmavconn                            [ 0.7 seconds ]            
Finished  <<< mav_state_machine_msgs                [ 1.1 seconds ]            
Starting  >>> mavros_msgs                                                      
Starting  >>> rotors_comm                                                      
Finished  <<< mav_msgs                              [ 1.6 seconds ]            
Starting  >>> rotors_description                                               
Finished  <<< rotors_description                    [ 0.3 seconds ]            
Finished  <<< mav_system_msgs                       [ 3.0 seconds ]            
Finished  <<< rotors_comm                           [ 2.1 seconds ]            
Starting  >>> rotors_evaluation                                                
Starting  >>> crazyflie_driver                                                 
Starting  >>> mav_planning_msgs                                                
Finished  <<< rotors_evaluation                     [ 0.6 seconds ]            
Starting  >>> rotors_control                                                   
Finished  <<< mavros_msgs                           [ 5.2 seconds ]            
Finished  <<< mav_planning_msgs                     [ 4.4 seconds ]            
Finished  <<< crazyflie_driver                      [ 6.8 seconds ]            
Starting  >>> rotors_joy_interface                                             
Starting  >>> mavros                                                           
_______________________________________________________________________________
Errors     << rotors_joy_interface:make /home/vishnu/agv_ws/logs/rotors_joy_interface/build.make.001.log
In file included from /home/vishnu/agv_ws/src/CrazyS-master/rotors_joy_interface/src/joy_crazyflie.cpp:18:0:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_joy_interface/include/rotors_joy_interface/joy_crazyflie.h:22:10: fatal error: mav_msgs/RollPitchYawrateThrustCrazyflie.h: No such file or directory
 #include <mav_msgs/RollPitchYawrateThrustCrazyflie.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rotors_joy_interface_crazyflie.dir/src/joy_crazyflie.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_joy_interface_crazyflie.dir/all] Error 2
make: *** [all] Error 2
cd /home/vishnu/agv_ws/build/rotors_joy_interface; catkin build --get-env rotors_joy_interface | catkin env -si  /usr/bin/make --jobserver-fds=7,8 -j; cd -
...............................................................................
Failed     << rotors_joy_interface:make             [ Exited with code 2 ]     
Failed    <<< rotors_joy_interface                  [ 2.7 seconds ]            
Abandoned <<< rqt_rotors                            [ Unrelated job failed ]   
Abandoned <<< mavros_extras                         [ Unrelated job failed ]   
Abandoned <<< rotors_gazebo_plugins                 [ Unrelated job failed ]   
Abandoned <<< rotors_gazebo                         [ Unrelated job failed ]   
Abandoned <<< test_mavros                           [ Unrelated job failed ]   
Finished  <<< mavros                                [ 3.5 seconds ]            
_______________________________________________________________________________
Errors     << rotors_control:make /home/vishnu/agv_ws/logs/rotors_control/build.make.001.log
In file included from /home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/mellinger_controller.cpp:21:0:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/include/rotors_control/mellinger_controller.h:27:11: fatal error: mav_msgs/DroneState.h: No such file or directory
  #include <mav_msgs/DroneState.h>
           ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mellinger_controller.dir/src/library/mellinger_controller.cpp.o] Error 1
make[1]: *** [CMakeFiles/mellinger_controller.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/internal_model_controller.cpp:17:0:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/include/rotors_control/internal_model_controller.h:22:10: fatal error: mav_msgs/DroneState.h: No such file or directory
 #include <mav_msgs/DroneState.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/internal_model_controller.dir/src/library/internal_model_controller.cpp.o] Error 1
make[1]: *** [CMakeFiles/internal_model_controller.dir/all] Error 2
In file included from /home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:17:0:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/include/rotors_control/roll_pitch_yawrate_thrust_crazyflie.h:69:33: error: ‘EigenRollPitchYawrateThrustCrazyflie’ in namespace ‘mav_msgs’ does not name a type
                 const mav_msgs::EigenRollPitchYawrateThrustCrazyflie& roll_pitch_yawrate_thrust);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/include/rotors_control/roll_pitch_yawrate_thrust_crazyflie.h:88:23: error: ‘EigenRollPitchYawrateThrustCrazyflie’ in namespace ‘mav_msgs’ does not name a type
             mav_msgs::EigenRollPitchYawrateThrustCrazyflie roll_pitch_yawrate_thrust_;
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In constructor ‘rotors_control::RollPitchYawrateThrustControllerCrazyflie::RollPitchYawrateThrustControllerCrazyflie()’:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:43:7: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
       roll_pitch_yawrate_thrust_.roll = 0;
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:43:7: note: suggested alternative: ‘SetRollPitchYawrateThrust’
       roll_pitch_yawrate_thrust_.roll = 0;
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
       SetRollPitchYawrateThrust
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In member function ‘void rotors_control::RollPitchYawrateThrustControllerCrazyflie::ControlMixer(double*, double*, double*, double*)’:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:116:5: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
     roll_pitch_yawrate_thrust_.thrust = roll_pitch_yawrate_thrust_.thrust * controller_parameters_.thrust_percentage_;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:116:5: note: suggested alternative: ‘SetRollPitchYawrateThrust’
     roll_pitch_yawrate_thrust_.thrust = roll_pitch_yawrate_thrust_.thrust * controller_parameters_.thrust_percentage_;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
     SetRollPitchYawrateThrust
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In member function ‘void rotors_control::RollPitchYawrateThrustControllerCrazyflie::RateController(double*, double*, double*)’:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:146:17: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
     r_command = roll_pitch_yawrate_thrust_.yaw_rate;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:146:17: note: suggested alternative: ‘SetRollPitchYawrateThrust’
     r_command = roll_pitch_yawrate_thrust_.yaw_rate;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
                 SetRollPitchYawrateThrust
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In member function ‘void rotors_control::RollPitchYawrateThrustControllerCrazyflie::AttitudeController(double*, double*)’:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:174:21: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
     theta_command = roll_pitch_yawrate_thrust_.pitch;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:174:21: note: suggested alternative: ‘SetRollPitchYawrateThrust’
     theta_command = roll_pitch_yawrate_thrust_.pitch;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
                     SetRollPitchYawrateThrust
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: At global scope:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:224:21: error: ‘EigenRollPitchYawrateThrustCrazyflie’ in namespace ‘mav_msgs’ does not name a type
     const mav_msgs::EigenRollPitchYawrateThrustCrazyflie& roll_pitch_yawrate_thrust) {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In member function ‘void rotors_control::RollPitchYawrateThrustControllerCrazyflie::SetRollPitchYawrateThrust(const int&)’:
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:226:3: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
   roll_pitch_yawrate_thrust_ = roll_pitch_yawrate_thrust;
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishnu/agv_ws/src/CrazyS-master/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:226:3: note: suggested alternative: ‘roll_pitch_yawrate_thrust’
   roll_pitch_yawrate_thrust_ = roll_pitch_yawrate_thrust;
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
   roll_pitch_yawrate_thrust
make[2]: *** [CMakeFiles/roll_pitch_yawrate_thrust_controller_crazyflie.dir/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp.o] Error 1
make[1]: *** [CMakeFiles/roll_pitch_yawrate_thrust_controller_crazyflie.dir/all] Error 2
make: *** [all] Error 2
cd /home/vishnu/agv_ws/build/rotors_control; catkin build --get-env rotors_control | catkin env -si  /usr/bin/make --jobserver-fds=7,8 -j; cd -
...............................................................................
Failed     << rotors_control:make                   [ Exited with code 2 ]     
Failed    <<< rotors_control                        [ 17.0 seconds ]           
[build] Summary: 16 of 23 packages succeeded.                                  
[build]   Ignored:   3 packages were skipped or are blacklisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: 5 packages were abandoned.                                
[build]   Failed:    2 packages failed.                                        
[build] Runtime: 25.0 seconds total.

**Comment by MvB12** [comment]
hey, can i please know if i had done any mistake or any insight in error I'm getting

**Comment by gsilano** [comment]
As you can see, the error originates from the `mav_msgs` package. Maybe, you are not using the right branch. Could you check that you are on the right one?

**Comment by MvB12** [comment]
I'm using this package(https://github.com/ethz-asl/mav_comm/)...I downloaded the master branch of this..If this is not the right branch can u point me at the right one?

**Comment by gsilano** [comment]
We found the issue. You need to clone and use this repository `https://github.com/gsilano/mav_comm.git`. Please, follow the instructions as detailed in the README.md file. Thanks!

**Comment by mengou8023** [comment]
hello，i'm learning your projects too and meet the same question,lacking Dronestate.h file and RollPitchYawrateThrustCrazyflie.h.This is my error:In file included from /home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/mellinger_controller.cpp:21:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/include/rotors_control/mellinger_controller.h:27:11: fatal error: mav_msgs/DroneState.h: 没有那个文件或目录
   27 |  #include <mav_msgs/DroneState.h>
      |           ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mellinger_controller.dir/build.make:63：CMakeFiles/mellinger_controller.dir/src/library/mellinger_controller.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2393：CMakeFiles/mellinger_controller.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
In file included from /home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/internal_model_controller.cpp:17:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/include/rotors_control/internal_model_controller.h:22:10: fatal error: mav_msgs/DroneState.h: 没有那个文件或目录
   22 | #include <mav_msgs/DroneState.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/internal_model_controller.dir/build.make:63：CMakeFiles/internal_model_controller.dir/src/library/internal_model_controller.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1300：CMakeFiles/internal_model_controller.dir/all] 错误 2
[ 38%] Linking CXX shared library /home/cs/CrazyS_ws/devel_isolated/rotors_control/lib/libcrazyflie_complementary_filter.so
[ 42%] Linking CXX shared library /home/cs/CrazyS_ws/devel_isolated/rotors_control/lib/libsensfusion6.so
[ 42%] Built target crazyflie_complementary_filter
[ 42%] Built target sensfusion6
In file included from /home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:17:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/include/rotors_control/roll_pitch_yawrate_thrust_crazyflie.h:69:33: error: ‘EigenRollPitchYawrateThrustCrazyflie’ in namespace ‘mav_msgs’ does not name a type; did you mean ‘EigenRollPitchYawrateThrustDeque’?
   69 |                 const mav_msgs::EigenRollPitchYawrateThrustCrazyflie& roll_pitch_yawrate_thrust);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 EigenRollPitchYawrateThrustDeque
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/include/rotors_control/roll_pitch_yawrate_thrust_crazyflie.h:88:23: error: ‘EigenRollPitchYawrateThrustCrazyflie’ in namespace ‘mav_msgs’ does not name a type; did you mean ‘EigenRollPitchYawrateThrustDeque’?
   88 |             mav_msgs::EigenRollPitchYawrateThrustCrazyflie roll_pitch_yawrate_thrust_;
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       EigenRollPitchYawrateThrustDeque
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In constructor ‘rotors_control::RollPitchYawrateThrustControllerCrazyflie::RollPitchYawrateThrustControllerCrazyflie()’:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:43:7: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
   43 |       roll_pitch_yawrate_thrust_.roll = 0;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In member function ‘void rotors_control::RollPitchYawrateThrustControllerCrazyflie::ControlMixer(double*, double*, double*, double*)’:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:116:5: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
  116 |     roll_pitch_yawrate_thrust_.thrust = roll_pitch_yawrate_thrust_.thrust * controller_parameters_.thrust_percentage_;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In member function ‘void rotors_control::RollPitchYawrateThrustControllerCrazyflie::RateController(double*, double*, double*)’:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:146:17: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
  146 |     r_command = roll_pitch_yawrate_thrust_.yaw_rate;
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In member function ‘void rotors_control::RollPitchYawrateThrustControllerCrazyflie::AttitudeController(double*, double*)’:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:174:21: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope
  174 |     theta_command = roll_pitch_yawrate_thrust_.pitch;
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: At global scope:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:224:21: error: ‘EigenRollPitchYawrateThrustCrazyflie’ in namespace ‘mav_msgs’ does not name a type; did you mean ‘EigenRollPitchYawrateThrustDeque’?
  224 |     const mav_msgs::EigenRollPitchYawrateThrustCrazyflie& roll_pitch_yawrate_thrust) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     EigenRollPitchYawrateThrustDeque
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp: In member function ‘void rotors_control::RollPitchYawrateThrustControllerCrazyflie::SetRollPitchYawrateThrust(const int&)’:
/home/cs/CrazyS_ws/src/CrazyS/rotors_control/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp:226:3: error: ‘roll_pitch_yawrate_thrust_’ was not declared in this scope; did you mean ‘roll_pitch_yawrate_thrust’?
  226 |   roll_pitch_yawrate_thrust_ = roll_pitch_yawrate_thrust;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |   roll_pitch_yawrate_thrust
[ 46%] Linking CXX shared library /home/cs/CrazyS_ws/devel_isolated/rotors_control/lib/libcrazyflie_onboard_controller.so
[ 46%] Built target crazyflie_onboard_controller
make[2]: *** [CMakeFiles/roll_pitch_yawrate_thrust_controller_crazyflie.dir/build.make:63：CMakeFiles/roll_pitch_yawrate_thrust_controller_crazyflie.dir/src/library/roll_pitch_yawrate_thrust_crazyflie.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2251：CMakeFiles/roll_pitch_yawrate_thrust_controller_crazyflie.dir/all] 错误 2
[ 50%] Linking CXX shared library /home/cs/CrazyS_ws/devel_isolated/rotors_control/lib/libposition_controller.so
[ 50%] Built target position_controller
[ 53%] Linking CXX shared library /home/cs/CrazyS_ws/devel_isolated/rotors_control/lib/libroll_pitch_yawrate_thrust_controller.so
[ 53%] Built target roll_pitch_yawrate_thrust_controller
[ 57%] Linking CXX shared library /home/cs/CrazyS_ws/devel_isolated/rotors_control/lib/liblee_position_controller.so
[ 57%] Built target lee_position_controller
make: *** [Makefile:141：all] 错误 2
<== Failed to process package 'rotors_control': 
  Command '['/home/cs/CrazyS_ws/install_isolated/env.sh', 'make', '-j16']' returned non-zero exit status 2.

Reproduce this error by running:
==> cd /home/cs/CrazyS_ws/build_isolated/rotors_control && /home/cs/CrazyS_ws/install_isolated/env.sh make -j16

Command failed, exiting.
Could you please give me some help?Thank you so much.

**Comment by mengou8023** [comment]
And I saw your reply to others,used https://github.com/gsilano/mav_comm.git,but still doesn't work.

**Comment by gsilano** [comment]
That’s strange. Try cleaning your workspace. It often helps. Just run `catkin clean` and then `catkin make` again.
