### ISSUE TITLE
Flying Height limitation

### ISSUE THREAD

**Issue by XuboLyu** [gsilano/CrazyS#42]
Hi @gsilano ,

Thanks for your work on this useful quadrotor simulated package.

Now I have a question when I fly crazyflie using "basic_crazyflie.world" and the launch file "crazyflie2_without_controller.launch". I send four same motor speed as command and try to make the drone fly vertically. I can see it take off successfully, but as it go on flying higher until around **7m** high, it suddenly start to flip and seems like collide with something invisible and start to fall down.

I feel very wired about this. In my code I do not set any height bound. And the basic crazyflie world actually has nothing but a single drone. What would be the possible reason behine this?

Look forward to your help! Thank you!

**Comment by gsilano** [comment]
Hi @XuboLyu!! What you have done is only valid in an ideal world, in which you consider only the vertical dynamics, completely forgetting about the lateral ones. When working in environments such as Gazebo these effects cannot be overlooked. 

Then, if you hold the propellers angular velocity value for the entire simulation, thereby exerting a constant force on the quad-rotor, why should the drone stop? It is normal for the drone to continue its motion until it encounters constraints of the simulated scenario in Gazebo (in this case the 7 months).

If you are trying to use a learning algorithm, you need to insert an exit option in your code. For example, if the height is greater than 3 meters, you can stop the simulation.
