### ISSUE TITLE
Adding a camera to crazyS 

### ISSUE THREAD

**Issue by ziyadAbouelenin** [gsilano/CrazyS#48]
Hello @gsilano , 

I want to add a camera to the crazyFlie, any idea how to do this? 

I found the [Adding a Camera to CrazyS] part in the wiki, but can you explain more or just point me to a reference if any. 

Thank you

**Comment by gsilano** [comment]
Hi! Thanks for your interest in CrazyS. As for your question, as it was complicated to explain how to add a simulated camera with CrazyS, I thought it was better to develop a sample example scenario.

As you can see from the commit above, I added the `crazyflie2_internal_model_controller_vi_sensor.launch` file to simulate Crazyflie with a VI sensor. To this, I added an RVIZ configuration file to see the camera images and the point cloud data.

I hope this can help.

**Comment by ziyadAbouelenin** [comment]
Thank you. This is very helpful.

**Comment by NithyaVijay** [comment]
Hi,
 I can run the Internal Model Controller (IMC) in CrazyS (ROS Melodic, Gazebo9).
Please clarify whether IMC is the same as the INDI controller mentioned on the Bitcraze website. Could you provide me with any documents or literature??

**Comment by gsilano** [comment]
Hi @NithyaVijay! Your question appears to be unrelated to this issue. It might be more appropriate to open a new one.
