### ISSUE TITLE
hovering example with enable_state_estimator=true

### ISSUE THREAD

**Issue by adrienohana** [gsilano/CrazyS#63]
Hello, 

I've recently installed CrazyS and have a problem with the hovering example. 

I'm on Ubuntu 18.04 and have Gazebo 9 installed. 

The hovering example works fine but when I enable the state estimator the rqt graph windows don't open and the drone goes up steadily along z, but then loses control and crashes. 

Any suggestions ? 

Thank you in advance, 

Adrien

**Comment by gsilano** [comment]
Hmm. Could you provide other references to understand what is going on?

**Comment by adrienohana** [comment]
Followed the installation instructions... just ran the example and it would not work.
I'm using the provided disc image in the end which works perfectly !
