### ISSUE TITLE
UAV Trajectory Control Problem

### ISSUE THREAD

**Issue by karaf17** [gsilano/CrazyS#65]
Hello There! 
We've written a publisher node which publishes to /crazyflie2/command/trajectory topic in type of MultiDOFJointTrajectory(). When we publish a trajectory via our node, we can see the publish command on terminal which we run roslaunch as "[ INFO] [1616880768.235356078, 23.238000000]: PositionController got first MultiDOFJointTrajectory message.". But the UAV is not going the point we published. It moves randomly. How can we solve this problem? Or Is there anything you can recommend for UAV controls?
Also we tried to publish a waypoint to UAV with using "rosrun rotors_gazebo waypoint_publish 5 5 1 0 __ns:=crazyflie2" but the result was the same.

**Comment by gsilano** [comment]
Hi @karaf17!! As described in the previous issues (e.g., #55), the current position controller does not allow any trajectory tracking. It was meant only to show the capabilities to simulate the behavior of the Crazyflie 2.0 nano-quadrotor. 
If you really want to implement a trajectory tracking controller (no matter if a trajectory or just waypoints are published over the network), then you need to design your own high-level and low-level control (this part could be omitted if you plan to reuse what is already there).

An interesting repository that is dealing with (i.e., trajectory tracking controller in a predictive manner) is available at the link: https://github.com/bcbarbara/crazyflie_nmpc.

I hope this helps. If you have any further questions, please do not hesitate. I'm not going to work on this project anytime soon, but I could help you out if you really want to start this activity.
