### ISSUE TITLE
Adding a payload connected to swarm

### ISSUE THREAD

**Issue by louiseracielle** [gsilano/CrazyS#66]
Hi, @gsilano!

I want to add a payload that is connected to the Crazyflie robots while still being able to control them individually. Is there any way to do this? 

I’ve tried creating my own model where I spawned four Crazyflie robots and attached a platform, but I found that it will only takeoff when the {robot_namespace}/base_link is the parent link of a joint. Doing so, however, will cause an error since the macro I created it in is being called four times, making each base_link a root link.

Thank you.

**Comment by gsilano** [comment]
Hi @louiseracielle! Regarding your question, you could take a look at the `crazyflie2_internal_model_controller_vi_sensor.launch` example in the `rotors_gazebo/launch` folder. In this example, a Visual Inertial Odometry sensor is attached to the drone body. So, you could follow the track, i.e., from the `crazyflie2_internal_model_controller_vi_sensor.launch` to `spawn_mav_crazyflie.launch`, and then `crazyflie2_base.xacro` in the `rotors_description/urdf` folder to understand how I handled it.

I think that reading the [book chapter](https://github.com/gsilano/CrazyS/wiki/Publications) can help you understand how to include a sensor, and in your case a payload, to the Crazy. Also, I recommend you to read the contents of[this page](http://wiki.ros.org/urdf/XML/link).

By model you mean simulation, launch file, right? If so, I do not understand what you did. Could you be more precise? Could you link here a video of your work? Please, note that the available control solution does not allow controlling the behavior of the Crazyflie when an additional mass is added to the system. Also, the available controller only implements a hovering example. Please, take a look at the past issues to understand more about that.
