### ISSUE TITLE
Setting waypoints

### ISSUE THREAD

**Issue by Kennjo** [gsilano/CrazyS#67]
I'm trying to get the UAV to follow a set path with pre-planned coordinates, any advice on how I could go about doing this will be much appreciated.

**Comment by gsilano** [comment]
Hi there! As discussed in #65, #44, and others, the current control implementation does not allow to track any trajectory or change the assigned waypoints (you can publish them over the ROS network but these points will not affect the control behavior). A simple hovering example was used to test the functionalities of the tool.

If you have any questions, please do not hesitate. Also, if you would like to add more features to the available version, we might think about this.
