### ISSUE TITLE
crazyflie2_swarm_hovering_example.launch runs but does not hover and can not be controlled.

### ISSUE THREAD

**Issue by terilgen** [gsilano/CrazyS#69]
We use Ubuntu 18.04 and ROS Melodic. When we try launch the simulation all the quadcopters are visible but the topics to control them do not start. We also tried to control them with xbox360 controller but it did not work as well.

**Comment by gsilano** [comment]
Hi @terilgen! This is a common problem when using the package with Ubuntu 18.04 and Gazebo 9. I highly recommend you follow what has been reported in other issues of this repository. The problem has been addressed many times, and quite sure that you will find the solution. If not, we can see together what is wrong with it.

**Comment by terilgen** [comment]
Hello again sir @gsilano , sorry for the late reply. I was dealing with my midterms. I have looked those issues and tried what they did but it did not work. When i use your VM file it works very well all topics are can be seen but when i try it on my computer with (Ubuntu 18.04 + ROS Melodic + Gazebo9) most of the important topics can not be seen. I added my errors and topic pictures on the attachment. 

This is from Ubuntu 18.04
![photo_2021-04-30_09-02-27](https://user-images.githubusercontent.com/63732492/116675392-765ad500-a9ae-11eb-830f-069552d68d42.jpg)

![photo_2021-04-30_09-02-28 (2)](https://user-images.githubusercontent.com/63732492/116675400-778c0200-a9ae-11eb-8f5e-6b9643f654ff.jpg)

![photo_2021-04-30_09-02-28](https://user-images.githubusercontent.com/63732492/116675402-778c0200-a9ae-11eb-8d85-fbfb9782bf66.jpg)

![Screenshot from 2021-04-30 11-53-37](https://user-images.githubusercontent.com/63732492/116675405-78249880-a9ae-11eb-8f3a-094fb42de7e3.png)

And this one is from Virtual Machine (Ubuntu 16.04)
![Screenshot_1](https://user-images.githubusercontent.com/63732492/116675406-78249880-a9ae-11eb-9d22-6f18185e9fff.png)

**Comment by gsilano** [comment]
I see your problem. Again, I think this is related to a wrong symbolic link. Have you checked the content of the `bashrc` file? As a quick test, you could compare the content of the file with that in the VM. That way, you can understand if something is missing there. Also, do not forget to source the file to the terminal line after any modifications.

Next time, please, do not post photos but try to attach to the issue the log file. Thanks!
