### ISSUE TITLE
cmake errors for rotors_gazebo_plugins

### ISSUE THREAD

**Issue by paradox56** [gsilano/CrazyS#7]
Hello,

I am trying to compile CrazyS for Ubuntu 18.04 and got the following errors. Any idea how can I fix this?

```
CMake Error at /home/xx/catkin_ws/src/CrazyS/rotors_gazebo_plugins/CMakeLists.txt:427 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:UUID::UUID,INTERFACE_INCLUDE_DIRECTORIES>

  Target "UUID::UUID" not found.


CMake Error:
  Error evaluating generator expression:

    $<TARGET_PROPERTY:UUID::UUID,INTERFACE_INCLUDE_DIRECTORIES>

  Target "UUID::UUID" not found.

```

**Comment by gsilano** [comment]
Hello!! Currently, CrazyS, as well as RotorS, is not compatible with the latest versions of ROS and Ubuntu. If you want to use it, I suggest you follow the instructions in the README.md file.
An update will be published in the next few days, so please star the repository to avoid losing updates.
